# general settings
server:
  port: 8080 # for local application launch

spring:
  # DataSource Configuration for PostgreSQL
  datasource:
#    url: jdbc:postgresql://localhost:5432/transaction_new_db # for use local PostgreSQL
    url: jdbc:postgresql://localhost:5440/transaction_new_db # for use PostgreSQL container
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use_sql_comments: true
      format_sql: true
      properties:
        hibernate.jdbc.time_zone: UTC
  # migration settings
  flyway:
    enabled: false # for local application launch
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/resources/graphql/

# environment variables for CassandraConfig class
CASSANDRA_CONTACT_POINTS: 127.0.0.1
CASSANDRA_KEYSPACE: my_keyspace
CASSANDRA_LOCAL_DATACENTER: datacenter1
CASSANDRA_PORT: 9043  # for local application launch but with use Cassandra container
CASSANDRA_SEEDS:  # it needs only IP-address
CASSANDRA_LISTEN_ADDRESS: db_cassandra
CASSANDRA_BROADCAST_ADDRESS: db_cassandra
CASSANDRA_RPC_ADDRESS: 0.0.0.0
CASSANDRA_BROADCAST_RPC_ADDRESS: db_cassandra

# graphql settings
graphql:
  timeoutMillis: 300000 # for debugging

# logging setting
logging:
  level:
    root: INFO # for debugging
    lab.solva.user.transaction: DEBUG
    org.springframework.boot.autoconfigure.logging: WARN
    org.springframework.boot.autoconfigure.cassandra: DEBUG
  file:
    name: logs/app.log
    append: true
  appenders:
    - type: file
      immediateFlush: true
      layout:
        type: pattern
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

#Command for launch application in terminal with application_local.yml
#java -jar ./build/libs/UserTransactionNew-0.0.1-SNAPSHOT.jar --spring.config.location=classpath:/application-local.yml