name: CI for Docker Compose Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Cassandra image
      run: |
        docker build -t cassandra-image -f docker_cassandra/Dockerfile .
        docker push cassandra-image

    - name: Build and push Postgres image
      run: |
        docker build -t postgres:alpine -f docker_postgres/Dockerfile .
        docker push postgres:alpine

    - name: Build and push App image
      run: |
        docker build -t app-user-transaction-new-image -f docker_app/Dockerfile .
        docker push app-user-transaction-new-image

    - name: Run Docker Compose
      run: docker-compose up -d --build