name: CI for Docker Compose Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Cassandra image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cassandra-image -f docker_cassandra/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/cassandra-image

    - name: Build and push Postgres image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/postgres:alpine -f docker_postgres/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/postgres:alpine

    - name: Build and push App image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app-user-transaction-new-image -f docker_app/Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/app-user-transaction-new-image

    - name: Run Docker Compose
      run: docker-compose up -d --build

    - name: Stop Docker Compose
      run: docker-compose down